### ISSUE TITLE
ItemStack length not respected

### ISSUE THREAD

**Issue by mazes-80** [minetest-mods/lavastuff#17] opened 2022-02-02 14:30 UTC
When you dig a block from defaut:clay you get four pieces default:clay_lump
When cooking a clay lump you get a default:clay_brick

For now if you dig a default:clay with a lavastuff tool it gives you only 1 default:clay_brick (should be 4)

I assume the problem will be the same for any block dropping a stack with more than 1 item in.

**Comment by LoneWolfHT** [comment] 2022-02-02 20:23
Try the latest commit https://github.com/minetest-mods/lavastuff/commit/94d6bd9b44516206be459a9427b442dff74e5d12

Make sure everything else cooks as expected too

**Comment by mckaygerhard** [comment] 2022-02-02 22:29
tested and it seems still not.. maybe in singleplayer or admin mode is not work.. i will test with normal player

**Comment by mazes-80** [comment] 2022-02-02 22:49
Le Wed, 02 Feb 2022 14:29:44 -0800,
Герхард PICCORO Lenz McKAY ***@***.***> a écrit :

> tested and it seems still not.. maybe in singleplayer or admin mode
> is not work.. i will test with normal player
> 

How did you install lavastuff, if it's not git version it will not
work, if you installed with latest git updates I'm sorry to hear this,
was just about to comment: works for me.

**Comment by LoneWolfHT** [comment] 2022-02-03 05:01
I haven't updated ContentDB yet because one of the latest commits causes a segfault with some setups

**Comment by mckaygerhard** [comment] 2022-02-03 14:52
please.. @LoneWolfHT @mazes-80  i used ,minetest 0.4.17 .. not the crap of 5.X .. and contendb its for windosers users that does not have enought braind to git cloning.. or command line setup

I property tested today, login as admin, put a node of default:clay later logout, then login as player and dig.. only gives me one clay.. i repeat but hosting a server too .. 

![screenshot_20220203_105006](https://user-images.githubusercontent.com/1571724/152366663-58bcbf49-db18-4aeb-b2f3-b0892cc48946.png)

**Comment by mckaygerhard** [comment] 2022-02-03 14:55
> if you installed with latest git updates I'm sorry to hear this, was just about to comment: works for me.

very rare.. maybecos i'm using 0.4.17.. the problem is that i not tested in the server i forced to 0.4.16 to act as server.. i dont know why its not working for me.. i updated the git remote with pull and merge.. 

i will do further investigations. but currently as is.. its fine cos at least it gives me a lump of clay_brick..

**Comment by mazes-80** [comment] 2022-02-03 21:24
Le Thu, 03 Feb 2022 06:52:58 -0800,
Герхард PICCORO Lenz McKAY ***@***.***> a écrit :

> and contendb its for windosers users that does not have enought
> braind to git cloning.. or command line setup

Some may prefer using contentdb even they are not windows user, as I do
on some station at home that are not hosting server.
For kids who just learned to read it's quite hard to use command
line in a foreign language and it is not related to be unbrainded,
cdb gui access is must have for them, thank dev for this feature.

I just asked you to ensure you updated via git, as in my case it works
as intended. As already said I can only state: works for me.

**Comment by mckaygerhard** [comment] 2022-02-07 03:29
yes i used git.. but it seem is my version.. still i play a lot MT 0.4.17 cos most phones only support that erver one.. i must test more deep but later.. cos currenly i so busy...

a note: @mazes-80  .. an interesting note: i work with kids.. those kids make me to build a live cd.. but that live only have a minimalistic window manager.. then asked 8 years ago in that moment "how to play".. the i said "learn to read".. later then they said "where is the game" i said "learn to command" .. today those kids are not so lazy as the current generation.. take in consideration that we train our kids to be prepared.. not to stay and wait for served things.. 

in fact now i have both miinetest5 and minetes4 own packages for thems.. at minenux project for venenux

**Comment by mckaygerhard** [comment] 2022-02-11 21:35
ITs working.. in MT 0.4.17 and 5.X .. you now can close this bug..  event updated master branch i clone fresh git and works.. 

![vokoscreen-2022-02-11_17-31-44](https://user-images.githubusercontent.com/1571724/153673203-a88e3107-07e7-4db1-ba14-ca5b7ae19b1f.gif)

**Closed** 2022-02-11 21:40 UTC
Labels: bug
